# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'APMInsight_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # 可以把这部分代码copy到您的Podfile文件中，执行pod install，安装对应组件
  # You can copy the code as follows to your Podfile, and excute "pod install" in command line to install our SDKs.
  # 可复制部分开始---
  #  Copyable section starts ---
  source 'https://github.com/volcengine/volcengine-specs.git'
  
  pod 'RangersAPM', '5.2.7', :subspecs => [
      'Crash',
      'WatchDog',
      'OOM',
      'LAG',
      'UserException',
      'Monitors',
      'UITrackers',
      'HybridPro',
      'MemoryGraph',
      'NetworkPro',
      'EventMonitor',
      'APMLog',
      'CrashProtector',
      'CPUException',
      'CN',
#      'Global',
      'Zombie',
      'BootingProtect',
      'MetricKit',
      'Disk',
      'SessionTracker',
      'GWPASan',
      'Coredump',
      'CloudCommand'
  ]
  
  pod 'RangersAPMDoctor', '2.0.0'
  
  # ---可复制部分结束
  # --- Copyable section ends
  
  # Pods for APMInsight_iOS
  
  # 按需接入部分开始---
  # Use as needed section starts---
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if "#{target}" == 'RangersAPM-RangersAPMPrivacyInfo'
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
  # ---按需接入部分结束
  # Use as needed section ends---

end

target 'APMInsight_iOS_extension' do
  use_frameworks!
  
  # 可以把这部分代码copy到您的Podfile文件中，执行pod install，安装对应组件
  # You can copy the code as follows to your Podfile, and excute "pod install" in command line to install our SDKs.
  # 可复制部分开始---
  #  Copyable section starts ---
  source 'https://github.com/volcengine/volcengine-specs.git'
  
  pod 'RangersAPMForExtension', '1.0.5'
  
  # ---可复制部分结束
  # --- Copyable section ends

end
